### ISSUE TITLE
Add setup files for audio extraction worker

### ISSUE THREAD

**Issue by greenw0lf** [beeldengeluid/dane-audio-extraction-worker#1]
- [x] `pyproject.toml`
- [x] `poetry.lock`
- [x] Workflow-related files
- [x] `Dockerfile`

**Comment by Veldhoen** [comment]
AUdio extraction: https://github.com/beeldengeluid/dane-video-segmentation-worker/commit/9cdcd1008124b2765d923c837f05005efbe7b1f0
(for inspiration)

**Comment by greenw0lf** [comment]
For Docker to work with WSL, I followed [this](https://docs.docker.com/desktop/wsl/#turn-on-docker-desktop-wsl-2)

Additionally, I had to do the following steps to be able to run `docker build`:

1. Create the docker group:
`sudo groupadd docker`

2. Add your user to the docker group.
`sudo usermod -aG docker ${USER}`

3. You would need to log out and log back in so that your group membership is re-evaluated. You can just `exit` WSL, then start it up again and it will work.
